version: "3.3"

services:
    
  web:
    build: .
    volumes:
      - ./src:/var/www/html/
    ports:
      - "8000:80"  
    
    env_file:
    - .env.dev

    depends_on:
      # this container should be started after the db container has been started
      - db

  db:
    image: mysql:5.7
    env_file:
      - .env.dev
    # Uncomment below line to build database from scratch - and populate tables. 
    # (do this once, then comment out line again)
    #command: --init-file /data/application/init.sql
    
    volumes:
      - ./src/model/sql:/data/application/
      - database_volume:/var/lib/mysql
  
volumes:
  database_volume: {}

