
### Denne fil skal redigeres, så dne passer til applikationen!

version: "3.3"
   
services:
  web:
    restart: always
    build: .
    volumes:
      - static_volume:/code/static
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - reverseproxy_proxynet

  nginx:
    image: nginx:latest
    restart: always
    hostname: bug-tracker-php.kristian.codes
    volumes:
      - static_volume:/code/static
      - type: bind
        source: ./nginx_config/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    expose:
      - 1337
    depends_on:
      - web
    environment:
      - VIRTUAL_HOST=bug-tracker-php.kristian.codes
      - VIRTUAL_PORT=1337
      - LETSENCRYPT_HOST=bug-tracker-php.kristian.codes
      - LETSENCRYPT_EMAIL=kmollerschmidt@gmail.com
      - url=https://bug-tracker-php.kristian.codes
    networks:
      - reverseproxy_proxynet

  db:
    image: mysql
    # documentation on the image: "https://hub.docker.com/_/mysql"
    restart: always
    environment:
        # mandatory (root user will be created with this password)
        MYSQL_ROOT_PASSWORD: insecure_dev_pwd

        # create additional database on image start up and a user with superuser priviledges
        MYSQL_DATABASE: bug_tracker
        MYSQL_USER: kristian
        MYSQL_PASSWORD: dev123
    ports:
      - "9906:3306"
      
      # Uncomment below line to build database from scratch - and populate tables. 
      #command: --init-file /data/application/init.sql
      
    volumes:
      - ./src/model/sql:/data/application/
      - my-datavolume:/var/lib/mysql
    networks:
      - reverseproxy_proxynet

    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
      - db
    networks:
      - reverseproxy_proxynet


volumes:
  database_volume: {}

networks:
  reverseproxy_proxynet:
    external: true