version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/

        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: bug_tracker

        ports:
            - "9906:3306"

        command: --init-file /data/application/init.sql
        volumes:
            - ./src/model/sql:/data/application/
    
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - '8080:80'
      restart: always
      environment:
          PMA_HOST: db
      depends_on:
          - db